# only direct deps may use exotic sources like git repositories or direct tarball URLs
blockExoticSubdeps: true

# only packages released at least 1.5 days ago can be installed:
minimumReleaseAge: 2160

# when set to no-downgrade, pnpm will fail if a package's trust level has decreased compared to previous releases
trustPolicy: no-downgrade
trustPolicyExclude:
  - 'semver@6.3.1'

packages:
  - 'apps/*'
  - 'demos/*'
  - 'packages/*'

allowBuilds:
  esbuild: true
  msw: true

overrides:
  'chokidar': '^5.0.0'
